version: '3.5'


services:
  eureka-server:
    image: interactive-web-shop-eureka:latest
    build: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://localhost:8761" ]
      interval: 5s
      timeout: 5s
      retries: 10



  gateway-service:
    image: interactive-web-shop-gateway:latest
    build: gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
      user-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://localhost:8080" ]
      interval: 5s
      timeout: 5s
      retries: 10



  shop-service:
    image: interactive-web-shop-shopping:latest
    build: shop-service
    container_name: shop-service
    ports:
      - "8082:8082"
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
      shop-service-db:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://localhost:8082" ]
      interval: 5s
      timeout: 5s
      retries: 10




  user-service:
    image: interactive-web-shop-users:latest
    build: user-service
    container_name: user-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
      user-service-db:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://localhost:8081" ]
      interval: 5s
      timeout: 5s
      retries: 10




  user-service-db:
    image: mysql:latest
    container_name: user-service-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: interactive-web-shop-users

  shop-service-db:
     image: mysql:latest
     container_name: shop-service-db
     restart: always
     ports:
     - "3308:3306"
     environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: interactive-web-shop-data