server:
  port: 8080

security:
  jwt:
    secret: MTA1NDQ2NDYyMjkxODQ3NjI0NjM4NjUxNTYxZGZnMTU2MTQ4ZGY5NDE4MTk0OTg=
    default_secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
  authentication:
    url: /api/v1/users/auth

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
      renewalIntervalInSecs: 10

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive