server:
  port: 8080

#security:
#  jwt:
#    secret: MTA1NDQ2NDYyMjkxODQ3NjI0NjM4NjUxNTYxZGZnMTU2MTQ4ZGY5NDE4MTk0OTg=
#  authentication:
#    url: users/auth

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    renewalIntervalInSecs: 10

spring:
  application:
    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: eureka-server
#          uri: lb://eureka-server
#          predicates:
#            - Path=/eureka/**
#          filters:
#            - RewritePath=/eureka/(?<segment>.*), /api/$\{segment}